### ISSUE TITLE
MPC reference inputs

### ISSUE THREAD

**Issue by zhangbaozhe** [uzh-rpg/rpg_mpc#7]
Hey guys, I've been using your library for our project. When I edit the code, I found that in the `MpcController` class, the method `setReference` also computes reference inputs. For example, [here](https://github.com/uzh-rpg/rpg_mpc/blob/33263db209105f716e204acc6481834fbd9bc778/src/mpc_controller.cpp#L184).

I am wondering, how's the performance if I do not compute any reference inputs and only set them to zeros. Will the optimization still converge? 

I'm debugging right now, and I have set them to zero. I do not know if this is a critical point for the performance of the whole controller. 

Thanks

**Comment by foehnx** [comment]
hmm, I think if you leave the inputs at zero it might converge but the problem is a bit malformed.
See, for most accelerations you will need non-zero thrusts (inputs).
If you set them just to zero then you basically change the cost term on inputs to minimize them, what might result in suboptimal control performance.
Effectively, this will trade-off the costs to [minimize thrusts (inputs)] <--against--> [minimize all other tracking errors].

**Comment by zhangbaozhe** [comment]
Thanks for the quick reply. 

I have run your code in PX4 sitl simulation to let the quadrotor follow a circle without the input references, and the result is good. However, now in our project, the state dimension reaches to 23, I want to let the quadrotor take off to a certain point (say (0,0,5) point) with other references setting to zeros or identities (the quaternions). I am not sure if ACADO can handle the optimal problem now. The behavior of this experiment is that after the quadrotor fly to the point at z = 5m, it becomes unstalbe and will drift to a certain direction and crash. I don't know if it is a problem of the ACADO side. 

Could you please share some general hints or suggesstions using ACADO?
